version = 0.1
[default.deploy.parameters]
stack_name = "circuit-breaker-sam"
resolve_s3 = true
s3_prefix = "circuit-breaker-sam"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
